/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 412ca0262dcc0b2f55187a853c153a06)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "ChatAgent" | "ChatStateDO";
  }
  interface Env {
    AI: Ai;
    DISCORD_BOT_TOKEN: string;
    DISCORD_PUBLIC_KEY: string;
    DISCORD_APPLICATION_ID: string;
    CHAT_AGENT: DurableObjectNamespace<import("./src/index").ChatAgent>;
    CHAT_STATE: DurableObjectNamespace<import("./src/index").ChatStateDO>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      "DISCORD_BOT_TOKEN" | "DISCORD_PUBLIC_KEY" | "DISCORD_APPLICATION_ID"
    >
  > {}
}
